@extends('user.base')
@section('user.content')
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
<p>ghalo</p>
@endsection